### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by Nowosad**
@KaniaKrzysztof - thanks for the package. I think it could be very useful. I cleaned and updated some docs. Do you plan to add spatial data inside of the package instead of forcing to downloading it from github and loading manually?

### CODE REVIEW

**Comment by KaniaKrzysztof** [comment]
Thank you for your work.
Shape files exceed CRAN 5mb package size limit so I wasn't able to put them into /data/.

**Comment by Nowosad** [comment]
What's the source of the shape files? There are some ways to add the data to the package, e.g. (1) compressing the files, (2) providing a function for data download, (3) creating a second non-CRAN package.

**Comment by KaniaKrzysztof** [comment]
Shape files came from my department internal resources used for: http://swaid.stat.gov.pl/AtlasRegionow/AtlasRegionowMapa.aspx

I've tried to compress files and reducing it's quality but sadly it wasn't enough to pass CRAN.

I'll try to add auto-download feature soon.

Thank you for your ideas🙏

**Comment by Nowosad** [comment]
Let me know if you need any help.

**Pull request merged**
